import Head from "next/head";
import Image from "next/image";
import { Canvas } from "../components/Canvas/Canvas";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Lab3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Canvas>Your browser does not support the HTML5 canvas tag.</Canvas>
      </main>
    </div>
  );
}
